export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOAD_PROJECTS = 'LOAD_PROJECTS';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
